import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Flow Motion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome back, Alton</h1>

        {/*  Section for task description and details*/}
        <section className={styles.content}>
          <section className={styles.detailsContainer}>
            <h2>Task Name</h2>
            <div>
                Difficulty
            </div>
            <div>
                Interruptions
            </div>
            <div>
                Estimated Duration
            </div>
            <div>
                Elapsed Duration
            </div>

            {/*Buttons container*/}
            <section className={styles.actionButtonContainer}>
              <button>Start Session</button>
              <button>Pause Session</button>
              <button>End Session</button>
            </section>
          </section>

          {/*Interactive component*/}
          <section>

          </section>
        </section>

      </main>


    </div>
  )
}
